// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type City struct {
	ID    string   `json:"id"`
	Text  string   `json:"text"`
	Meteo []*Meteo `json:"meteo"`
}

type Meteo struct {
	ID        string     `json:"id"`
	Day       string     `json:"day"`
	MeteoType *MeteoType `json:"meteoType"`
}

type MeteoType struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewMeteo struct {
	Day       string `json:"day"`
	CityID    string `json:"cityId"`
	MeteoType string `json:"meteoType"`
}
